// ========================================
// GuangDianLocation - 坐标点选择系统
// ========================================

plugins {
    id 'java'
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.6-R0.1-SNAPSHOT'
    compileOnly project(':plugins:RPGCore')
    
    // 数据库驱动
    implementation 'mysql:mysql-connector-java:8.0.33'
    implementation 'org.xerial:sqlite-jdbc:3.45.1.0'
}

jar {
    archiveBaseName.set('GuangDianLocation')
}
