// ========================================
// GuangDianName - 称号显示系统
// ========================================

plugins {
    id 'java'
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.6-R0.1-SNAPSHOT'
    compileOnly project(':plugins:RPGCore')
    compileOnly project(':plugins:GuangDianArmorStats')
    compileOnly files('../GuangDianArmorStats/libs/PlaceholderAPI.jar')
    compileOnly 'net.luckperms:api:5.4'
}

jar {
    archiveBaseName.set('GuangDianName')
}
