plugins {
    id 'java'
}

repositories {
    flatDir { dirs '../RPGCore/build/libs' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.6-R0.1-SNAPSHOT'
    compileOnly files('libs/RPGCore-1.0.0.jar')
    implementation 'com.google.code.gson:gson:2.10.1'
}

jar {
    archiveBaseName.set('GuangDianMCP')
}
