plugins {
    id 'java'
}

repositories {
    mavenCentral()
    flatDir { dirs 'libs' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.6-R0.1-SNAPSHOT'
    compileOnly project(':plugins:RPGCore')
    compileOnly files('../GuangDianArmorStats/libs/PlaceholderAPI.jar')
    compileOnly files('libs/Vault.jar')
    
    implementation 'com.zaxxer:HikariCP:5.1.0'
}

jar {
    archiveBaseName.set('GuangDianMonthlyCard')
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

// 处理资源文件
processResources {
    from('src/main/resources') {
        include '*.yml'
        duplicatesStrategy = DuplicatesStrategy.INCLUDE
    }
}
