// ========================================
// GuangDianMarket - 市场系统
// ========================================

plugins {
    id 'java'
}

repositories {
    flatDir {
        dirs 'libs'
    }
    maven {
        name = "papermc"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21-R0.1-SNAPSHOT'
    compileOnly files('libs/RPGCore.jar')
    compileOnly files('libs/GuangDianPoints.jar')
    compileOnly files('libs/PlaceholderAPI.jar')
    compileOnly files('libs/Vault.jar')
}

jar {
    archiveBaseName.set('GuangDianMarket')
}
