plugins {
    id 'java'
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.6-R0.1-SNAPSHOT'
    compileOnly files('libs/RPGCore-1.0.0.jar')
    compileOnly name: 'MythicMobs'
}

jar {
    archiveBaseName.set('GuangDianBlockDrop')
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
