name: GuangDianArmorStats
version: 1.0.0
main: cn.guangdian.armorstats.GuangDianArmorStats
author: GuangDian
description: RPG装备属性插件
api-version: 1.21
softdepend:
  - RPGCore
  - PlaceholderAPI
  - MythicMobs
  - GuangDianSocket

commands:
  armorstats:
    description: 查看或重载装备属性
    usage: /<command> [view/reload]
    aliases:
      - stats
