// ========================================
// GuangDianBoard - 计分板系统
// ========================================

plugins {
    id 'java'
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.6-R0.1-SNAPSHOT'
    compileOnly project(':plugins:RPGCore')
    compileOnly project(':plugins:GuangDianArmorStats')
    compileOnly 'net.luckperms:api:5.4'
    compileOnly files('../GuangDianArmorStats/libs/PlaceholderAPI.jar')
}

jar {
    archiveBaseName.set('GuangDianBoard')
}
